# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python_project\miaopai_videoupload\videos_get\getVideoUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_getVideoUi(object):
    def setupUi(self, getVideoUi):
        getVideoUi.setObjectName("getVideoUi")
        getVideoUi.resize(833, 654)
        self.videoCat = QtWidgets.QGroupBox(getVideoUi)
        self.videoCat.setGeometry(QtCore.QRect(0, 70, 881, 41))
        self.videoCat.setObjectName("videoCat")
        self.yule = QtWidgets.QCheckBox(self.videoCat)
        self.yule.setGeometry(QtCore.QRect(60, 20, 51, 16))
        self.yule.setObjectName("yule")
        self.yingshi = QtWidgets.QCheckBox(self.videoCat)
        self.yingshi.setGeometry(QtCore.QRect(110, 20, 51, 16))
        self.yingshi.setObjectName("yingshi")
        self.shenghuo = QtWidgets.QCheckBox(self.videoCat)
        self.shenghuo.setGeometry(QtCore.QRect(160, 20, 51, 16))
        self.shenghuo.setObjectName("shenghuo")
        self.youxi = QtWidgets.QCheckBox(self.videoCat)
        self.youxi.setGeometry(QtCore.QRect(210, 20, 51, 16))
        self.youxi.setObjectName("youxi")
        self.shehui = QtWidgets.QCheckBox(self.videoCat)
        self.shehui.setGeometry(QtCore.QRect(260, 20, 51, 16))
        self.shehui.setObjectName("shehui")
        self.yinyue = QtWidgets.QCheckBox(self.videoCat)
        self.yinyue.setGeometry(QtCore.QRect(310, 20, 51, 16))
        self.yinyue.setObjectName("yinyue")
        self.tuijian = QtWidgets.QCheckBox(self.videoCat)
        self.tuijian.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.tuijian.setObjectName("tuijian")
        self.yule_2 = QtWidgets.QCheckBox(self.videoCat)
        self.yule_2.setGeometry(QtCore.QRect(450, 40, 51, 16))
        self.yule_2.setObjectName("yule_2")
        self.kaiyan = QtWidgets.QCheckBox(self.videoCat)
        self.kaiyan.setGeometry(QtCore.QRect(410, 20, 51, 16))
        self.kaiyan.setObjectName("kaiyan")
        self.gaoxiao = QtWidgets.QCheckBox(self.videoCat)
        self.gaoxiao.setGeometry(QtCore.QRect(360, 20, 51, 16))
        self.gaoxiao.setObjectName("gaoxiao")
        self.kaiyan_2 = QtWidgets.QCheckBox(self.videoCat)
        self.kaiyan_2.setGeometry(QtCore.QRect(490, 40, 51, 16))
        self.kaiyan_2.setObjectName("kaiyan_2")
        self.daimeng = QtWidgets.QCheckBox(self.videoCat)
        self.daimeng.setGeometry(QtCore.QRect(460, 20, 51, 16))
        self.daimeng.setObjectName("daimeng")
        self.xiangsheng = QtWidgets.QCheckBox(self.videoCat)
        self.xiangsheng.setGeometry(QtCore.QRect(510, 20, 71, 16))
        self.xiangsheng.setObjectName("xiangsheng")
        self.videSource = QtWidgets.QGroupBox(getVideoUi)
        self.videSource.setGeometry(QtCore.QRect(0, 10, 881, 41))
        self.videSource.setObjectName("videSource")
        self.check_toutiao = QtWidgets.QCheckBox(self.videSource)
        self.check_toutiao.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.check_toutiao.setObjectName("check_toutiao")
        self.haokan = QtWidgets.QCheckBox(self.videSource)
        self.haokan.setGeometry(QtCore.QRect(80, 20, 71, 16))
        self.haokan.setObjectName("haokan")
        self.btn_getvideo = QtWidgets.QPushButton(getVideoUi)
        self.btn_getvideo.setGeometry(QtCore.QRect(0, 130, 75, 23))
        self.btn_getvideo.setObjectName("btn_getvideo")
        self.btn_download = QtWidgets.QPushButton(getVideoUi)
        self.btn_download.setGeometry(QtCore.QRect(80, 130, 91, 23))
        self.btn_download.setObjectName("btn_download")
        self.line_videoSave = QtWidgets.QLineEdit(getVideoUi)
        self.line_videoSave.setGeometry(QtCore.QRect(410, 130, 381, 20))
        self.line_videoSave.setReadOnly(True)
        self.line_videoSave.setPlaceholderText("")
        self.line_videoSave.setObjectName("line_videoSave")
        self.lab_videoPosition = QtWidgets.QLabel(getVideoUi)
        self.lab_videoPosition.setGeometry(QtCore.QRect(320, 130, 81, 20))
        self.lab_videoPosition.setObjectName("lab_videoPosition")
        self.btn_selectSavePath = QtWidgets.QPushButton(getVideoUi)
        self.btn_selectSavePath.setGeometry(QtCore.QRect(800, 130, 31, 23))
        self.btn_selectSavePath.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/ico/Arzo_Icons_018.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_selectSavePath.setIcon(icon)
        self.btn_selectSavePath.setIconSize(QtCore.QSize(16, 16))
        self.btn_selectSavePath.setObjectName("btn_selectSavePath")
        self.table_videos = QtWidgets.QTableWidget(getVideoUi)
        self.table_videos.setGeometry(QtCore.QRect(-5, 161, 841, 491))
        self.table_videos.setObjectName("table_videos")
        self.table_videos.setColumnCount(0)
        self.table_videos.setRowCount(0)
        self.btn_delsel = QtWidgets.QPushButton(getVideoUi)
        self.btn_delsel.setGeometry(QtCore.QRect(180, 130, 71, 23))
        self.btn_delsel.setObjectName("btn_delsel")
        self.btn_delall = QtWidgets.QPushButton(getVideoUi)
        self.btn_delall.setGeometry(QtCore.QRect(260, 130, 61, 23))
        self.btn_delall.setObjectName("btn_delall")

        self.retranslateUi(getVideoUi)
        QtCore.QMetaObject.connectSlotsByName(getVideoUi)

    def retranslateUi(self, getVideoUi):
        _translate = QtCore.QCoreApplication.translate
        getVideoUi.setWindowTitle(_translate("getVideoUi", "网上视频收集下载器"))
        self.videoCat.setTitle(_translate("getVideoUi", "视频分类"))
        self.yule.setText(_translate("getVideoUi", "娱乐"))
        self.yingshi.setText(_translate("getVideoUi", "影视"))
        self.shenghuo.setText(_translate("getVideoUi", "生活"))
        self.youxi.setText(_translate("getVideoUi", "游戏"))
        self.shehui.setText(_translate("getVideoUi", "社会"))
        self.yinyue.setText(_translate("getVideoUi", "音乐"))
        self.tuijian.setText(_translate("getVideoUi", "推荐"))
        self.yule_2.setText(_translate("getVideoUi", "娱乐"))
        self.kaiyan.setText(_translate("getVideoUi", "开眼"))
        self.gaoxiao.setText(_translate("getVideoUi", "搞笑"))
        self.kaiyan_2.setText(_translate("getVideoUi", "开眼"))
        self.daimeng.setText(_translate("getVideoUi", "呆盟"))
        self.xiangsheng.setText(_translate("getVideoUi", "相声小品"))
        self.videSource.setTitle(_translate("getVideoUi", "视频来源"))
        self.check_toutiao.setText(_translate("getVideoUi", "今日头条"))
        self.haokan.setText(_translate("getVideoUi", "好看视频"))
        self.btn_getvideo.setText(_translate("getVideoUi", "获取视频"))
        self.btn_download.setText(_translate("getVideoUi", "下载选中视频"))
        self.lab_videoPosition.setText(_translate("getVideoUi", "视频下载位置："))
        self.btn_delsel.setText(_translate("getVideoUi", "删除未选中"))
        self.btn_delall.setText(_translate("getVideoUi", " 清空"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    getVideoUi = QtWidgets.QDialog()
    ui = Ui_getVideoUi()
    ui.setupUi(getVideoUi)
    getVideoUi.show()
    sys.exit(app.exec_())

